export const user = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
}

export const card = {
    CHANGE_HIDDEN_STATE: 'CARD_CHANGE_HIDDEN_STATE',
    ADD_ITEM: 'CARD_ADD_ITEM',
    REMOVE: 'CARD_REMOVE',
    INCREMENT: 'CARD_INCREMENT',
    DECREMENT: 'CARD_DECREMENT',
}